alias ls='ls --color=auto'
alias ll='ls -alF' 
alias la='ls -A' 
alias l='ls -CF'
alias vless='/usr/share/vim/vimcurrent/macros/less.sh'
alias sl='ls'
alias ra='sudo /etc/init.d/apache2 restart'
alias t='todo.sh'
alias v='vim'
alias gv='gvim'
