alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias sl='ls'
alias ra='sudo /etc/init.d/apache2 restart'
alias t='tree -L 2'
alias v='vim'
alias gv='gvim'
alias look='/usr/share/vim/vimcurrent/macros/less.sh'
alias follow='tail -F'
alias agrep='ack-grep'
